name: Despliegue ASP.NET a IIS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest # Usa un runner de Windows, ya que compilarás para IIS (Windows)

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configurar .NET Core SDK (o Framework)
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x' 

    - name: Restaurar dependencias
      run: dotnet restore "TareasMVC/TareasMVC.csproj"

    - name: Compilar proyecto
      run: dotnet build "TareasMVC/TareasMVC.csproj" -c Release

      #APLICAR MIGRACIONES A LA BASE DATOS
    - name: Aplicar migraciones de EF Core a SQL server
      shell: powershell
      run: |
        dotnet tool install --global dotnet-ef --version 9.0.0
        $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
        dotnet ef database update --project "TareasMVC/TareasMVC.csproj" --startup-project "TareasMVC/TareasMVC.csproj" --connection '$env:DB_CONNECTION_STRING' --assembly "TareasMVC/bin/Debug/net9.0/TareasMVC.dll" 
      env:
        ConnectionStrings__DefaultConnection: ${{secrets.DB_CONNECTION_STRING}}


    #Despliegue de la aplicación
    - name: Compilar y Publicar
      run: dotnet publish "TareasMVC/TareasMVC.csproj" -c Release -o ${{ env.ASSEMBLY_PATH }} --no-restore
      env:
        ASSEMBLY_PATH: ${{ github.workspace }}/app/publish

    - name: Despliegue con Web Deploy a IIS
      uses: ChristopheLav/iis-deploy@v1
      with:
        website-name: 'sistemas.trainmar.mx'
        msdeploy-service-url: ${{ secrets.IIS_SERVER_URL }}
        msdeploy-username: ${{ secrets.WEB_DEPLOY_USERNAME }}
        msdeploy-password: ${{ secrets.WEB_DEPLOY_PASSWORD }}
        source-path: ${{ env.ASSEMBLY_PATH }}
        skip-extra-files: false
        
    - name: Verificar Despliegue
      run: echo "Despliegue completado y ejecutándose en ${{ secrets.IIS_SERVER_URL }}"